env:
  node: true
  es2023: true
extends:
  - eslint:recommended
parserOptions:
  sourceType: module
rules:
  comma-dangle: error
  indent: [error, 4]
  max-len: [error, 120, { ignoreStrings: true, ignoreTemplateLiterals: true }]
  no-constant-condition: [error, { checkLoops: false }]
  no-multiple-empty-lines: error
  no-shadow: error
  no-unused-vars: [error, { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }]
  object-curly-spacing: [error, always]
  quotes: [error, single, { avoidEscape: true }]
  semi: error
  strict: error
