name: Build and Test

on:
  pull_request:
  push:
    branches:
    - master

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc

jobs:
  build:
    name: OS=${{ matrix.os }} ICVM=${{ matrix.icvm }} PROFILE=${{ matrix.profile }})
    runs-on: ${{ matrix.os }}
    env:
      ICVM_PROFILE: ${{ matrix.profile }}
      ICVM_TYPE: ${{ matrix.icvm }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        icvm: [c, cs, go]
        profile: [n, y]
        exclude:
          - icvm: cs
            profile: y
          - icvm: go
            profile: y

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Test
      run: make test
