name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc

jobs:
  build:
    name: OS=${{ matrix.os }} VM=${{ matrix.icvm }} P=${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    env:
      ICVM_PROFILE: ${{ matrix.profile }}
      ICVM_TYPE: ${{ matrix.icvm }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        icvm: [c, cs, go, rust]
        profile: [n, y]
        exclude:
          - icvm: cs
            profile: y
          - icvm: rust
            profile: y

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
        if: matrix.icvm == 'cs'

      - name: Build
        run: make build

      - name: Test
        run: make test
