name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc

jobs:
  build:
    name: OS=${{ matrix.os }} VM=${{ matrix.icvm }}
    runs-on: ${{ matrix.os }}
    env:
      ICVM_TYPE: ${{ matrix.icvm }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        icvm: [c, cs, go, js, rust]
        include:
          - os: ubuntu-latest
            icvm: c-ext
          - os: macOS-latest
            icvm: c-ext
          - os: ubuntu-latest
            icvm: cl

    steps:
      - name: Checkout xzintbit
        uses: actions/checkout@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        if: matrix.icvm == 'cs'

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
        if: matrix.icvm == 'js'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
        if: matrix.icvm == 'go'

      - name: Setup Steel Bank Common Lisp
        run: |
          sudo apt install sbcl cl-quicklisp
          sbcl --non-interactive --load /usr/share/common-lisp/source/quicklisp/quicklisp.lisp --eval '(quicklisp-quickstart:install)'
          cp vms/cl/.sbclrc ~/.sbclrc
        if: matrix.icvm == 'cl'

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Build additional tools
        run: make build-tools
        if: matrix.os != 'windows-latest' # no c-ext vm on windows
