name: Build and Test

on:
  pull_request:
  push:
    branches:
    - master

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build IntCode VM
      run: |
        cd vm
        npm ci
        npm run build --if-present
    - name: Build Assembler
      run: |
        ./make.sh
    - name: Test Assembler
      run: |
        ./test.sh
