name: Build and Test

on:
  pull_request:
  push:
    branches:
    - master

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  build-linux:
    name: Test on ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Build Assembler
      run: ./make.sh
      if: runner.os != 'Windows'
    - name: Build Assembler
      run: make.cmd
      if: runner.os == 'Windows'

    - name: Test Assembler
      run: ./test.sh
      if: runner.os != 'Windows'
    - name: Test Assembler
      run: test.cmd
      if: runner.os == 'Windows'
