name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc

jobs:
  build:
    name: OS=${{ matrix.os }} VM=${{ matrix.icvm }} P=${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    env:
      ICVM_PROFILE: ${{ matrix.profile }}
      ICVM_TYPE: ${{ matrix.icvm }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        icvm: [c, cs, go, js, rust]
        profile: [n, y]
        exclude:
          - icvm: cs
            profile: y
          - icvm: js
            profile: y
          - icvm: rust
            profile: y
        include:
          - os: ubuntu-latest
            icvm: cl
            profile: n

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
        if: matrix.icvm == 'cs'

      - name: Setup Steel Bank Common Lisp
        run: |
          sudo apt install sbcl cl-quicklisp
          sbcl --non-interactive --load /usr/share/common-lisp/source/quicklisp/quicklisp.lisp --eval '(quicklisp-quickstart:install)'
          cp vms/cl/.sbclrc ~/.sbclrc
        if: matrix.icvm == 'cl'

      - name: Build
        run: make build

      - name: Test
        run: make test
