name: Build and Test

on:
  pull_request:
  push:
    branches:
    - master

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc 

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Build Assembler (bash)
      if: runner.os != 'Windows'
      run: ./build.sh
    - name: Build Assembler (cmd)
      if: runner.os == 'Windows'
      shell: cmd
      run: build

    - name: Test Assembler (bash)
      if: runner.os != 'Windows'
      run: ./test.sh
    - name: Test Assembler (cmd)
      if: runner.os == 'Windows'
      shell: cmd
      run: test
