name: Build and Test

on:
  pull_request:
  push:
    branches:
    - master

env:
  FORCE_COLOR: 1
  TERM: xterm-color
  CC: gcc

jobs:
  build:
    name: Test on ${{ matrix.os }} (profile=${{ matrix.profile }})
    runs-on: ${{ matrix.os }}
    env:
      ICVM_PROFILE: ${{ matrix.profile }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        profile: [n, y]

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Test
      run: make test
